title: Cybernet Solutions
description: Software solutions for productivity and personal growth
remote_theme: pages-themes/slate@v0.2.0
url: "https://cybernetsolutions.co"
header_pages:
    - momentum.md
    - support.md
    - privacy.md
