title: Cybernet Solutions
description: Software solutions
sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: dark
  nav_pages:
    - about.md
  hide_site_feed_link: true  # `false` or `null` by default
remote_theme: "jekyll/minima@c6e74bb"
url: "https://cybernet-dev.github.io"
