title: Cybernet Solutions
description: Software solutions for productivity and personal growth
theme: slate
url: "https://cybernetsolutions.co"
header_pages:
    - momentum.md
    - support.md
    - privacy.md
